version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      #      - image: circleci/android:api-30
      - image: cimg/android:2023.08
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

#      - restore_cache:
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      #      - run:
      #          name: Run Tests
      #          command: ./gradlew lint test
      - run: ./gradlew assembleDebug

      - store_artifacts:
          path: app/build/outputs/apk/
          destination: reports
      - store_test_results:
          path: app/build/test-results

      - run:
          name: Install Fastlane
          command: gem install fastlane

      - run:
          name: Build and Deploy APK
          command: fastlane release

workflows:
  version: 2
  build-deploy:
    jobs:
      - build