version: 2
orbs:
  android: circleci/android@1.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: ccistaging/android:api-30
        environment:
          JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Check Java Installation
          command: java -version
      - run:
          name: Set Java Version
          command: |
            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-17.0.1/bin/java 3
            sudo update-alternatives --config java

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: List APK Directory
          command: ls -l app/build/outputs/apk
      - run:
          name: Assemble Debug
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: artifact-files
      - run:
          name: Run Tests
          command: ./gradlew test