version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      #      - image: circleci/openjdk:17.0.8
      - image: cimg/android:2023.08
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew androidDependencies
      - run: ./gradlew lint test

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      #      - run:
      #          name: Run Tests
      #          command: ./gradlew lint test
      - run: ./gradlew assembleDebug

      - store_artifacts:
          path: app/build/outputs/apk/
          destination: reports
      - store_test_results:
          path: app/build/test-results