version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
      - persist_to_workspace:
          root: app/build/outputs/apk/debug
          paths:
            - app-debug.apk