version: 2
orbs:
  android: circleci/android@1.0
jobs:
  build:
    working_directory: ~/code
    docker:
      # Choose the appropriate Docker image for your project's needs.
      # - image: circleci/android:api-25-alpha
      - image: ccistaging/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Chmod permissions # If permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      # Generate APK
      - run: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      # Run tests!test
      - run: ./gradlew test