version: 2.1

jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-30

    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Build APK
          command: ./gradlew assembleDebug

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: debug-apks